# multi-stage build
# 1. Подготовка образа для сборки приложения
FROM node:16-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

# 2. Итоговый образ
FROM node:16-alpine AS production
WORKDIR /app
COPY --from=builder /app/package*.json ./
RUN npm install --omit=dev
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/ecosystem.config.js ./ecosystem.config.js
RUN npm install -g pm2
EXPOSE 3000
CMD ["pm2-runtime", "ecosystem.config.js"]
